### ISSUE TITLE
xDnsRecord Absent does not check for the target

### ISSUE THREAD

**Issue by CraigTolley** [dsccommunity/xDnsServer#129]
I ma using the xDnsRecord resource to control which domain controllers provide LDAPS, so I have a configuration which specifies whether a DNS record should exist or not for a given domain controller. 

However, the computers which I am requiring the record to be absent are failing to apply. I believe it is all around this line, which is simply detecting that a record exists with the name, and it shouldn't.

https://github.com/dsccommunity/xDnsServer/blob/2a8ea7f52c1a29637a5fc895105b8defeddbe4d8/source/DSCResources/MSFT_xDnsRecord/MSFT_xDnsRecord.psm1#L257

The resource is picking up my other valid ldaps records, and attempting to delete them, failing as it doesn't have permissions on the records. 

The 'quick fix' is to have the test check the target as well, and only remove the records that match the target (if specified in the configuration). This may be an unexpected change in behaviour of the module though. 

I'm wondering if the best way to handle this is through some option flag, which chooses if the 'absent' record should apply to all records which match the name or just the record which matches all the configured options, or if the behaviour depends on the options specified, as exampled below.

e.g this would remove everything with the name 'ldaps.example.com'
`xDnsRecord 'Ldaps' {
        Name      = 'ldaps'
        Zone       = example.com
        Ensure    = 'Absent'
}
`

e.g this would remove everything with the name 'ldaps.example.com' that is an A record with the given IP address
`xDnsRecord 'Ldaps' {
        Name      = 'ldaps'
        Zone       = example.com
        Target     = 192.168.1.11
        Type       = 'ARecord'
        Ensure    = 'Absent'
}
`

What does everyone else think about this?

**Comment by johlju** [comment]
Labeling it as a bug and help wanted so someone in the community can run with this. But it would  be better to add the resource https://github.com/dsccommunity/xDnsServer/issues/145 since the plan is that the resource xDnsRecord will be deprecated in the future.

**Comment by johlju** [comment]
This resource is now deprecated and will be removed in the near future. New resources covers the functionality.
