### ISSUE TITLE
DnsRecordMx: Add additional properties

### ISSUE THREAD

**Issue by Sudman1** [dsccommunity/xDnsServer#140]
### Description

In line with #34, a DSCResource for MX records should be created. For consistency, the resource should be named `xDnsRecordMx`.

#### Mandatory

- ZoneName: Specifies the name of a DNS zone.
- Name: Specifies the name of a DNS server resource record object.
- MailExchange: Specifies the FQDN of the host that is acting as a mail exchanger for the owner.
- Preference: Specifies the priority for this resource record among other resource records that belong to the same owner, where a lower value has a higher priority.

#### Optional

- AgeRecord: Indicates that the DNS server uses a time stamp for the resource record that this cmdlet adds. A DNS server can scavenge resource records that have become stale based on a time stamp.
- AllowUpdateAny: Indicates that any authenticated user can update a resource record that has the same owner name.
- DnsServer: Specifies a DNS server. If you do not specify this parameter, the command runs on the local system. You can specify an IP address or any value that resolves to an IP address, such as a fully qualified domain name (FQDN), host name, or NETBIOS name.
- TTL: Specifies the Time to Live (TTL) value, in seconds, for a resource record. Other DNS servers use this length of time to determine how long to cache a record.
- ZoneScope: Specifies the name of a zone scope.
- Ensure: Denotes whether the record should be `Present` or `Absent`

### Special considerations or limitations

Not all mandatory properties need to be key properties. Please review the syntax and purpose of this record type to make the best determination of which properties should be key properties.

All proposed properties above options come straight from the `Add-DnsServerResourceRecord` help syntax with two exceptions:

- `TimeToLive` has been changed to `TTL`
- `ComputerName` has been changed to `DnsServer`

**Comment by johlju** [comment]
Reopening this since this issue proposes additional properties. Also renamed the issue title to reflect that.

**Comment by Sudman1** [comment]
The DnsServer cmdlet uses the terms `Name`, `MailExchange`, and `Preference`
The current MX record resource uses `Name`, `Target`, and `Priority`
I find the following to be more descriptive, and therefore more user-friendly: `EmailDomain`, `MailExchange`, and `Priority`

Unless there are any objections (@johlju, @indented-automation, @gaelcolas, I'm looking at you specifically), I plan to use this naming in the new class-based resource.

**Comment by johlju** [comment]
I don't mind your suggestion. Are you about to PR this in? If so I wait for it before releasing 2.0.0.

**Comment by Sudman1** [comment]
I should have something for tomorrow morning.
