### ISSUE TITLE
DnsRecordCName: New resource proposal

### ISSUE THREAD

**Issue by Sudman1** [dsccommunity/xDnsServer#147]
### Description

In line with #34, a DSCResource for CNAME records should be created. For consistency, the resource should be named `DnsRecordCName`.

#### Mandatory

- ZoneName: Specifies the name of a DNS zone.
- Name: Specifies the name of a DNS server resource record object.
- HostNameAlias: Specifies a a canonical name target for a CNAME record. This must be a fully qualified domain name (FQDN).

#### Optional

- DnsServer: Specifies a DNS server. If you do not specify this parameter, the command runs on the local system. You can specify an IP address or any value that resolves to an IP address, such as a fully qualified domain name (FQDN), host name, or NETBIOS name.
- TimeToLive: Specifies the Time to Live (TTL) value, in seconds, for a resource record. Other DNS servers use this length of time to determine how long to cache a record.
- ZoneScope: Specifies the name of a zone scope.
- Ensure: Denotes whether the record should be `Present` or `Absent`

### Special considerations or limitations

Not all mandatory properties need to be key properties. Please review the syntax and purpose of this record type to make the best determination of which properties should be key properties.

All proposed properties above options come straight from the `Add-DnsServerResourceRecord` help syntax with two exceptions:

- `ComputerName` has been changed to `DnsServer`

**Comment by johlju** [comment]
Labeling this high priority since this is one of three resource that will help us deprecate xDnsSrvRecord.
