### ISSUE TITLE
xDnsRecordSrv: Add additional properties

### ISSUE THREAD

**Issue by Sudman1** [dsccommunity/xDnsServer#149]
### Description

In line with #34, a DSCResource for SRV records should be created. For consistency, the resource should be named `xDnsRecordSrv`.

#### Mandatory

- ZoneName: Specifies the name of a DNS zone.
- Name: Specifies the name of a DNS server resource record object.
- DomainName: Specifies the name of a domain.
- Port: Specifies the port where the server listens for the service.
- Priority: Specifies the priority of a DNS server. Clients try to contact the server that has the lowest priority.
- Weight: Specifies a value for the weight of the target host for a resource record. You can use this parameter when you have multiple hosts that have an identical priority. Use of the host is proportional to its weight.

#### Optional

- DnsServer: Specifies a DNS server. If you do not specify this parameter, the command runs on the local system. You can specify an IP address or any value that resolves to an IP address, such as a fully qualified domain name (FQDN), host name, or NETBIOS name.
- TimeToLive: Specifies the Time to Live (TTL) value, in seconds, for a resource record. Other DNS servers use this length of time to determine how long to cache a record.
- ZoneScope: Specifies the name of a zone scope.
- Ensure: Denotes whether the record should be `Present` or `Absent`

### Special considerations or limitations

Not all mandatory properties need to be key properties. Please review the syntax and purpose of this record type to make the best determination of which properties should be key properties.

All proposed properties above options come straight from the `Add-DnsServerResourceRecord` help syntax with two exceptions:

- `ComputerName` has been changed to `DnsServer`

**Comment by johlju** [comment]
This resource have been merge already but we should update the existing resource with optional parameters as needed.

**Comment by johlju** [comment]
@Sudman1 I wonder if we should rename ` TTL` to `TimeToLive` to be more inline with the other parameters and avoid abbreviations? If so we should do that before we release 2.0, and make sure PR #124 does it as well. What is something you considered by renaming it TTL? 

/cc @jcuzzi

**Comment by Sudman1** [comment]
I'm not married to TTL. I used TTL because that was what was called out on some of the issues and I believe was the nomenclature in @jcuzzi resource here. Consistency with the DNS server module naming is valid.

**Comment by Sudman1** [comment]
I'm working this now - to include the TTL -> TimeToLive issue. Might as well get all the resources using the full property sets for the 2.0 release.

**Comment by Sudman1** [comment]
- `AgeRecord` is a `[switch]` parameter on `Add-DnsServerResourceRecord`. Therefore, I will implement it as a boolean with a default value `$false`
- `AllowUpdateAny` - same as `AgeRecord`
- `ZoneScope` is a `[string]` parameter on `Add-DnsServerResourceRecord`. It will be treated like TimeToLive without the validation.

**Comment by Sudman1** [comment]
Use of `ZoneScope` could cause a key value conundrum.

Consider a split-brain DNS setup with two zone scopes: "external" and the default in which no scope is specified. In theory, the `Zone`, `SymbolicName`, `Protocol`, `Port`, and `Target` could be the same in both scopes. In practice, this is unlikely.

I see two possible ways to implement this:

1. Simply assume the case that in practice, the values will always differ and implement it as an Optional parameter.
2. Make it a key parameter in the schema MOF to allow for duplicates across scopes, but set it up as an optional parameter with a dummy default value such as "_DEFAULT_" which is later used in a conditional to not use the `-ZoneScope` parameter in the `Add-DnsServerResourceRecord` cmdlet.

I tend to favor option 2, but I'm not sure if it would work.

**Comment by Sudman1** [comment]
Another conundrum: There is no way to determine whether `AllowUpdatesAny` has been used. And more to the point, it doesn't make sense to use this property with DSC since DSC should be resetting the value every time it is updated by an external entity.

As such, I do not plan to implement `AllowUpdatesAny`.
