### ISSUE TITLE
xDnsRecordSrv: Weight and Priorty should be Key properties

### ISSUE THREAD

**Issue by johlju** [dsccommunity/xDnsServer#158]
We must change the properties Weight and Priority to Key properties.

https://github.com/dsccommunity/xDnsServer/blob/730101cb1f2c0d894ee4fc3b949b1e8fbd286cb8/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.schema.mof#L9-L10

All these properties shown in the image uniquely identifies a SRV record in Microsoft DNS. It is shown if trying to add a SRV record with the properties that already exists. 

![image](https://user-images.githubusercontent.com/7189721/107558924-ae3a5380-6bdb-11eb-8e44-132f4d105040.png)

**Comment by johlju** [comment]
@Sudman1 I tried this and it looks like the above needs to resolved. 🤔 Do you have any thoughts?

**Comment by johlju** [comment]
Maybe Microsoft DNS allows this but there is no point for the resource to actually allow having se same host name with different weights or priorites... 🤔

**Comment by Sudman1** [comment]
That's correct. The values are mandatory, but having the same host specified with a different weight doesn't make sense to me. I feel like making priority and weight key properties would make managing SRV records more difficult than needed.

**Comment by Sudman1** [comment]
For instance, if you needed to change the weight of a record, right now it can be modified. If weight is a key property, two entries are needed to make the change: remove the old one and add the new one.

**Comment by Sudman1** [comment]
Reading through the [SRV RFC](https://tools.ietf.org/html/rfc2782), multiple SRV records for the same service can be created for load balancing purposes. It seems that there is nothing to prohibit multiple service records with the same target. But it would be nonsensical to do so, as you couldn't load balance a system with itself and it would complicate the priority/weight calculations unnecessarily. 

Therefore, I believe the current implementation is the most correct for the intended purpose of SRV records, but I am open to other opinions and am happy to follow consensus.

**Comment by johlju** [comment]
> But it would be nonsensical to do so, as you couldn't load balance a system with itself and it would complicate the priority/weight calculations unnecessarily. 

I agree. Closing this issue, and if someone can give a valid scenario that we can't see right now we can revisit this. 🙂
