### ISSUE TITLE
BUILD FAILURE: xDnsServer: Cannot build the module

### ISSUE THREAD

**Issue by Sudman1** [dsccommunity/xDnsServer#211]
#### Details of the scenario you tried and the problem that is occurring

`build.ps1` fails at *Generating Conceptual Help*. It has an incorrect path to the `xDnsServer.psd1` file.

This may be a problem upstream with latest Sampler version.

#### Verbose logs showing the problem

```
===============================================================================
			GENERATE CONCEPTUAL HELP
This task generates conceptual help for DSC resources.
-------------------------------------------------------------------------------
  /pack/build/Generate_Conceptual_Help
  /home/vsts/work/1/s/output/RequiredModules/DscResource.DocGenerator/0.8.1/tasks/Generate_Conceptual_Help.build.ps1:64

ERROR: Cannot find path '/home/vsts/work/1/s/output/xDnsServer/xDnsServer.psd1' because it does not exist.
At /home/vsts/work/1/s/output/RequiredModules/Sampler/0.109.6/Sampler.psm1:472 char:19
+ … oduleInfo = Import-PowerShellDataFile -Path $BuiltModuleManifestPath  …
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At /home/vsts/work/1/s/output/RequiredModules/DscResource.DocGenerator/0.8.1/tasks/Generate_Conceptual_Help.build.ps1:64 char:1
+ task Generate_Conceptual_Help {
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At /home/vsts/work/1/s/build.ps1:290 char:13
+             task $workflow $workflowItem
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At /home/vsts/work/1/s/build.ps1:290 char:13
+             task $workflow $workflowItem
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Build FAILED. 9 tasks, 1 errors, 0 warnings 00:00:04.2003029
Import-PowerShellDataFile: /home/vsts/work/1/s/output/RequiredModules/Sampler/0.109.6/Sampler.psm1:472
Line |
 472 |  … oduleInfo = Import-PowerShellDataFile -Path $BuiltModuleManifestPath  …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path
     | '/home/vsts/work/1/s/output/xDnsServer/xDnsServer.psd1'
     | because it does not exist.
```
#### Suggested solution to the issue

Unknown. Autodetect path?

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

N/A

#### The operating system the target node is running

Windows 10 and Linux (Azure Dev Ops Agent)

#### Version and build of PowerShell the target node is running

Name                           Value
----                           -----
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

and presumably version 7 on Linux?

#### Version of the DSC module that was used

HEAD

**Comment by Sudman1** [comment]
### Confirmed:

Sampler 0.109.6 breaks the build process.

### Workaround:

Hard-coded version 0.109.5 in the RequiredModules.psd1 file.

**Comment by johlju** [comment]
Thanks for reporting! @gaelcolas is working on stuff, I think there was a dependency issue that Sampler needed to be released before PR https://github.com/dsccommunity/DscResource.DocGenerator/pull/65 in DocGenerator was merged (since it uses Sampler too).

**Comment by johlju** [comment]
We should change this back to `latest` once Sampler and DocGenerator are working together again. When PR  dsccommunity/DscResource.DocGenerator#65 is merged.

https://github.com/dsccommunity/xDnsServer/blob/6b8daba558bcaccc1dc273b2a22385b35661710e/RequiredModules.psd1#L16

**Comment by gaelcolas** [comment]
This should be fixed, let me know if not.

**Comment by gaelcolas** [comment]
And the problem was that all tasks needed to be updated with sampler, so Sampler.GitHubTasks needed to be pinned also, and DscResource.DocGenerator was not yet updated...

All should be working now if set to latest.
Sorry for the issue, I thought I could update all at once, but yesterday was a bit crazy at work!
