### ISSUE TITLE
xDnsRecord: Deprecate resource 

### ISSUE THREAD

**Issue by johlju** [dsccommunity/xDnsServer#220]
There are now separate resources that covers the functionality for the resource xDnsRecord (see https://github.com/dsccommunity/xDnsServer/projects/1). So suggest we deprecate the resource, and then later remove the resource when we rename the module to DnsServerDsc.

**Comment by Sudman1** [comment]
Along with deprecation, should we close issues #67 (PR #108), #98, #129, and #171 - which are concerned with the xDnsRecord resource - as moot?

**Comment by johlju** [comment]
Yes, that was my plan. Close anything related to xDnsRecord. It will be removed as soon as we released 2.0.0.0, as DnsServerDsc will be released as 3.0.0.0 shortly after.
