### ISSUE TITLE
More DNS record types

### ISSUE THREAD

**Issue by DrProbie** [dsccommunity/xDnsServer#34]
Hi there...

This module is excellent to work with - as far as it goes.

I wish to see at least support for SRV, MX, PTR and AAAA records come in soon. It would make it so much more useful for me.

If nobody else is half ways or more with it, I'd like to give it a shot.  After reading through the discussions under Pull request #14, I agree with the approach to keep the record management in one resource, and in line with Add-DnsServerResourceRecord.

If there are no comments, I'll go ahead and implement, and then take the heat from the Pull request.

**Comment by iainbrighton** [comment]
Hi @DrProbie - it's on my ever-growing To-Do list! Therefore, if you're happy to implement these, then go for it 👍

**Comment by DrProbie** [comment]
Fine...!  I'll start with one, follow it all the way through then move on... :)

**Comment by iainbrighton** [comment]
That's the spirit and a good plan! There may be some discussion/comments about coding style and test implementation etc. on the first commit. However, once you've got that nailed down, the rest should be easy 😉

**Comment by DrProbie** [comment]
I'll do my best to nail that one on the first, but you know how it is...! :D

**Comment by iainbrighton** [comment]
@DrProbie Have you had a chance to look at adding these additional record types?

**Comment by DrProbie** [comment]
Only briefly, been waiting for the more quiet summertime that now is upon us…  So I expect to start doing something serious about it now in July.  Are you looking for something to do…? ☺

Mvh/Jonni

**Comment by johlju** [comment]
PTR is being worked on in PR #60. The other should be added as well. I will relabel this as Help Wanted, so that someone in the community can run with this.

**Comment by 1800Zeta** [comment]
Thank you @indented-automation 

I think we need SRV and A records initially. Looking at the Add-DnsServerResourceRecord cmdlet I think you might be right and it would be worth keeping to a smaller subset. Would it be a case of create xDnsARecord, xDnsAAARecord, xDnsMXRecord etc?

**Comment by 1800Zeta** [comment]
Thank you @indented-automation I am more than happy to wait a few days and see what's what.

**Comment by johlju** [comment]
There was a resource added xDnsRecord a while back. If this issue is not covered by that resource, please comment on or re-open this issue.

**Comment by johlju** [comment]
Reopening this since I thing there are more resources that need to be added before closing this. Or split up this issue into separate issues.

**Comment by johlju** [comment]
Closing this issue sine @Sudman1 have opened new resource proposal issues for each record that. Thank you! 🙇
