### ISSUE TITLE
xDNSServerPrimaryZone - failure to pass Dynamic Update parameter

### ISSUE THREAD

**Issue by Roblarson** [dsccommunity/xDnsServer#37]
Attempting to do a simple deployment of a Primary Zone via Azure Automation DSC pull server.

```
configuration DNSsample
{

    $PrimaryZoneName = $DomainName
    $ZoneFile = "$PrimaryZoneName.dns"
    $DynamicUpdateMode = $DynamicUpdateSetting


Import-DscResource -module xDNSServer
Node $AllNodes.Where{$_.Role -eq "Primary DNS"}.Nodename
{
    xDnsServerPrimaryZone addPrimaryZone
    {
        Ensure        = 'Present'
        Name          = $PrimaryZoneName
        ZoneFile      = $ZoneFile
        DynamicUpdate = $DynamicUpdateMode
    }


}
}

# sample Configuration Data for DNS

$ConfigData = @{
    AllNodes = @(
        @{
            Nodename = "SBDNS"
            Role = "Primary DNS"
            DomainName = "dsc-test.contoso.com"
            DynamicUpdateSetting = "None"
            PSDscAllowPlainTextPassword = $True

        RetryCount = 20 
        RetryIntervalSec = 30 
    }

)

}

Start-AzureRmAutomationDscCompilationJob  -ResourceGroupName "SBUXTest" -AutomationAccountName "SBTest" -ConfigurationName "DNSsample" -ConfigurationData $ConfigData
```

Upload the configuration, then compile config with ConfigData

Fails the compile with the following error
```
xDnsServer\xDnsServerPrimaryZone : '' is not a valid value for property 'DynamicUpdate' on class 
'xDnsServerPrimaryZone'. Please change the value to one of the following strings: None, NonsecureAndSecure.
At Compile-ConfigurationV2:29 char:29
- 
  - CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
  - FullyQualifiedErrorId : InvalidValueForProperty,xDnsServer\xDnsServerPrimaryZone
```
Tried with both values with no luck.

**Comment by iainbrighton** [comment]
Sorry - replying to this via email. How are you passing in the ConfigurationData? Shouldn't it be:

DynamicUpdate = $node.DynamicUpdateSetting?

**Comment by Roblarson** [comment]
Ok I fixed that issue, but wanted to pass on that your examples are not complete.

You cannot create the Primary zone unless you have the Windows feature dependency on the configuration files. The configuration will compile, but te application fails with the dependency missing.

configuration DNSsample
{
    Import-DscResource -module xDnsServer

    Node $AllNodes.Where{$_.Role -eq "Primary DNS"}.Nodename
    {
        WindowsFeature InstallDNS
        {
            Ensure = 'Present'
            Name = "DNS"
            IncludeAllSubFeature = $True
        }

        xDnsServerPrimaryZone addPrimaryZone
        {
            Ensure        = 'Present'
            Name          = $Node.Name
            ZoneFile      = "$($Node.DomainName).dns"
            DynamicUpdate = $Node.DynamicUpdate
            DependsOn = "[WindowsFeature]InstallDNS"
        }  
    }
}

**Comment by johlju** [comment]
There was a test added to the latest merged integration tests. Also the DNS feature must be installed for the resources to work, but it can either be installed by `WindowsFeature` or by any other means. But pushed a change in PR #182 to explain this in the Wiki.
