### ISSUE TITLE
xDnsServerSetting: 'DsAvailable' Key not in Test- and Set-TargetResource in Version 1.9.0.0

### ISSUE THREAD

**Issue by pedrr** [dsccommunity/xDnsServer#66]
The Property 'DsAvailable' is returend by Get-TargetResource but cannot be tested.

> Error Message: The PowerShell DSC resource  returned results that are not valid from Get-TargetResource. The DsAvailable key is not a valid property in the corresponding DSC resource schema file. The results from Get-TargetResource must be in a Hashtable format. The keys in the Hashtable must be the same as the properties in the corresponding DSC resource schema file.
> Message ID: GetOperationResultInvalidResultFormat

i think this property is missing in the Test and Set Statement.

**Comment by johlju** [comment]
If this property `DsAvailable` can be set to a value, then it is missing in the schema.mod, and in the Set- and Test-TargetResource function. If `DsAvailable` is a read only value, then schema.mof should be updated to add this property with the `Read` qualifier to make it a read-only property.

**Comment by rchristman89** [comment]
@johlju  Should this issue be closed?

**Comment by johlju** [comment]
Yes looks like this was fixed in PR https://github.com/dsccommunity/xDnsServer/pull/69.
