### ISSUE TITLE
xDnsServerDiagnostics: New resource proposal

### ISSUE THREAD

**Issue by japatton** [dsccommunity/xDnsServer#86]
### Description

Some DNS Server Diagnostic settings can not be directly configured with the current xDnsServerSetting resource. I would like to create a new resource to add this functionality leveraging the Get-DnsServerDiagnostics and Set-DnsServerDiagnostics. 

### Proposed properties

SaveLogsToPersistentStorage
Queries
Answers
Notifications
Update
QuestionTransactions
UnmatchedResponse
SendPackets
ReceivePackets
TcpPackets
UdpPackets
FullPackets
FilterIPAddressList
EventLogLevel
UseSystemEventLog
EnableLoggingToFile
EnableLogFileRollover
LogFilePath
MaxMBFileSize
WriteThrough
EnableLoggingForLocalLookupEvent
EnableLoggingForPluginDllEvent
EnableLoggingForRecursiveLookupEvent
EnableLoggingForRemoteServerEvent
EnableLoggingForServerStartStopEvent
EnableLoggingForTombstoneEvent
EnableLoggingForZoneDataWriteEvent
EnableLoggingForZoneLoadingEvent

**Comment by johlju** [comment]
This was added in PR https://github.com/dsccommunity/xDnsServer/pull/92
