### ISSUE TITLE
Support Server Policies

### ISSUE THREAD

**Issue by 1800Zeta** [dsccommunity/xDnsServer#95]
Have had a look through open issues. Not sure if it's been mentioned before.

https://docs.microsoft.com/en-us/windows-server/networking/dns/deploy/dns-policies-overview

At the moment, we are looking at implementing a policy for a specific use case. However it's all PowerShell configured. I was considering writing a custom script that DSC could run for certain servers to "self configure" but then started digging in to the DSC resource.

Has anyone been looking at this at all? I've not written a DSC resource before but can make an attempt at it.

**Comment by 1800Zeta** [comment]
Thank you @indented-automation 

So, I have forked this off, created a folder (MSFT_xDnsServerClientSubnet) and created the file MSFT_xDnsServerClientSubnet.psm1 here https://github.com/1800Zeta/xDnsServer/tree/DnsServerPolicies/DSCResources/MSFT_xDnsServerClientSubnet

Do I need to have all aspects of DNS Policies working before I look to do a PR or once I am happy this works will just this be OK for now? Sorry for the Q's first time doing this

Thanks

**Comment by 1800Zeta** [comment]
@indented-automation once I have completed the Zone Scopes, the next task is to modify the Resource Records. Which one should I use? DNSRecord or DNSARecord? I saw some discussion on these two resources and would like to double check. Thank you

**Comment by johlju** [comment]
As per your question. xDnsRecord is the one that replaces xDnsARecord. xDnsARecord will be removed on the next release.

Where are we with this issue? Is there still something we are tracking with it? I see several PR's have been merged that references this one.

**Comment by johlju** [comment]
I'm closing this issue for now, please reopen if something else must be discussed in this issue. If there are more resources that should be created, please open new issues, one per resource to propose using the template for resource proposals.
